// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/info_server/info_server.proto)

#include <iomanip>

#include "info_server_impl.h"
#include "plugins/info_server/info_server.h"

namespace mavsdk {

using FlightInfo = InfoServer::FlightInfo;
using Identification = InfoServer::Identification;
using Product = InfoServer::Product;
using Version = InfoServer::Version;

InfoServer::InfoServer(System& system) :
    PluginBase(),
    _impl{std::make_unique<InfoServerImpl>(system)}
{}

InfoServer::InfoServer(std::shared_ptr<System> system) :
    PluginBase(),
    _impl{std::make_unique<InfoServerImpl>(system)}
{}

InfoServer::~InfoServer() {}

std::pair<InfoServer::Result, InfoServer::FlightInfo> InfoServer::provide_flight_information() const
{
    return _impl->provide_flight_information();
}

std::pair<InfoServer::Result, InfoServer::Identification> InfoServer::provide_identification() const
{
    return _impl->provide_identification();
}

std::pair<InfoServer::Result, InfoServer::Product> InfoServer::provide_product() const
{
    return _impl->provide_product();
}

std::pair<InfoServer::Result, InfoServer::Version> InfoServer::provide_version() const
{
    return _impl->provide_version();
}

std::pair<InfoServer::Result, double> InfoServer::provide_speed_factor() const
{
    return _impl->provide_speed_factor();
}

bool operator==(const InfoServer::FlightInfo& lhs, const InfoServer::FlightInfo& rhs)
{
    return (rhs.time_boot_ms == lhs.time_boot_ms) && (rhs.flight_uid == lhs.flight_uid);
}

std::ostream& operator<<(std::ostream& str, InfoServer::FlightInfo const& flight_info)
{
    str << std::setprecision(15);
    str << "flight_info:" << '\n' << "{\n";
    str << "    time_boot_ms: " << flight_info.time_boot_ms << '\n';
    str << "    flight_uid: " << flight_info.flight_uid << '\n';
    str << '}';
    return str;
}

bool operator==(const InfoServer::Identification& lhs, const InfoServer::Identification& rhs)
{
    return (rhs.hardware_uid == lhs.hardware_uid) && (rhs.legacy_uid == lhs.legacy_uid);
}

std::ostream& operator<<(std::ostream& str, InfoServer::Identification const& identification)
{
    str << std::setprecision(15);
    str << "identification:" << '\n' << "{\n";
    str << "    hardware_uid: " << identification.hardware_uid << '\n';
    str << "    legacy_uid: " << identification.legacy_uid << '\n';
    str << '}';
    return str;
}

bool operator==(const InfoServer::Product& lhs, const InfoServer::Product& rhs)
{
    return (rhs.vendor_id == lhs.vendor_id) && (rhs.vendor_name == lhs.vendor_name) &&
           (rhs.product_id == lhs.product_id) && (rhs.product_name == lhs.product_name);
}

std::ostream& operator<<(std::ostream& str, InfoServer::Product const& product)
{
    str << std::setprecision(15);
    str << "product:" << '\n' << "{\n";
    str << "    vendor_id: " << product.vendor_id << '\n';
    str << "    vendor_name: " << product.vendor_name << '\n';
    str << "    product_id: " << product.product_id << '\n';
    str << "    product_name: " << product.product_name << '\n';
    str << '}';
    return str;
}

bool operator==(const InfoServer::Version& lhs, const InfoServer::Version& rhs)
{
    return (rhs.flight_sw_major == lhs.flight_sw_major) &&
           (rhs.flight_sw_minor == lhs.flight_sw_minor) &&
           (rhs.flight_sw_patch == lhs.flight_sw_patch) &&
           (rhs.flight_sw_vendor_major == lhs.flight_sw_vendor_major) &&
           (rhs.flight_sw_vendor_minor == lhs.flight_sw_vendor_minor) &&
           (rhs.flight_sw_vendor_patch == lhs.flight_sw_vendor_patch) &&
           (rhs.os_sw_major == lhs.os_sw_major) && (rhs.os_sw_minor == lhs.os_sw_minor) &&
           (rhs.os_sw_patch == lhs.os_sw_patch) &&
           (rhs.flight_sw_git_hash == lhs.flight_sw_git_hash) &&
           (rhs.os_sw_git_hash == lhs.os_sw_git_hash);
}

std::ostream& operator<<(std::ostream& str, InfoServer::Version const& version)
{
    str << std::setprecision(15);
    str << "version:" << '\n' << "{\n";
    str << "    flight_sw_major: " << version.flight_sw_major << '\n';
    str << "    flight_sw_minor: " << version.flight_sw_minor << '\n';
    str << "    flight_sw_patch: " << version.flight_sw_patch << '\n';
    str << "    flight_sw_vendor_major: " << version.flight_sw_vendor_major << '\n';
    str << "    flight_sw_vendor_minor: " << version.flight_sw_vendor_minor << '\n';
    str << "    flight_sw_vendor_patch: " << version.flight_sw_vendor_patch << '\n';
    str << "    os_sw_major: " << version.os_sw_major << '\n';
    str << "    os_sw_minor: " << version.os_sw_minor << '\n';
    str << "    os_sw_patch: " << version.os_sw_patch << '\n';
    str << "    flight_sw_git_hash: " << version.flight_sw_git_hash << '\n';
    str << "    os_sw_git_hash: " << version.os_sw_git_hash << '\n';
    str << '}';
    return str;
}

std::ostream& operator<<(std::ostream& str, InfoServer::Result const& result)
{
    switch (result) {
        case InfoServer::Result::Unknown:
            return str << "Unknown";
        case InfoServer::Result::Success:
            return str << "Success";
        case InfoServer::Result::InformationNotReceivedYet:
            return str << "Information Not Received Yet";
        case InfoServer::Result::NoSystem:
            return str << "No System";
        default:
            return str << "Unknown";
    }
}

} // namespace mavsdk