// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/info_server/info_server.proto)

#include "info_server/info_server.grpc.pb.h"
#include "plugins/info_server/info_server.h"

#include "mavsdk.h"
#include "lazy_plugin.h"
#include "log.h"
#include <atomic>
#include <cmath>
#include <future>
#include <limits>
#include <memory>
#include <sstream>
#include <vector>

namespace mavsdk {
namespace mavsdk_server {

template<typename InfoServer = InfoServer, typename LazyPlugin = LazyPlugin<InfoServer>>
class InfoServerServiceImpl final : public rpc::info_server::InfoServerService::Service {
public:
    InfoServerServiceImpl(LazyPlugin& lazy_plugin) : _lazy_plugin(lazy_plugin) {}


    template<typename ResponseType>
    void fillResponseWithResult(ResponseType* response, mavsdk::InfoServer::Result& result) const
    {
        auto rpc_result = translateToRpcResult(result);

        auto* rpc_info_server_result = new rpc::info_server::InfoServerResult();
        rpc_info_server_result->set_result(rpc_result);
        std::stringstream ss;
        ss << result;
        rpc_info_server_result->set_result_str(ss.str());

        response->set_allocated_info_server_result(rpc_info_server_result);
    }




    static std::unique_ptr<rpc::info_server::FlightInfo> translateToRpcFlightInfo(const mavsdk::InfoServer::FlightInfo &flight_info)
    {
        auto rpc_obj = std::make_unique<rpc::info_server::FlightInfo>();


            
        rpc_obj->set_time_boot_ms(flight_info.time_boot_ms);
            
        
            
        rpc_obj->set_flight_uid(flight_info.flight_uid);
            
        

        return rpc_obj;
    }

    static mavsdk::InfoServer::FlightInfo translateFromRpcFlightInfo(const rpc::info_server::FlightInfo& flight_info)
    {
        mavsdk::InfoServer::FlightInfo obj;


            
        obj.time_boot_ms = flight_info.time_boot_ms();
            
        
            
        obj.flight_uid = flight_info.flight_uid();
            
        
        return obj;
    }





    static std::unique_ptr<rpc::info_server::Identification> translateToRpcIdentification(const mavsdk::InfoServer::Identification &identification)
    {
        auto rpc_obj = std::make_unique<rpc::info_server::Identification>();


            
        rpc_obj->set_hardware_uid(identification.hardware_uid);
            
        
            
        rpc_obj->set_legacy_uid(identification.legacy_uid);
            
        

        return rpc_obj;
    }

    static mavsdk::InfoServer::Identification translateFromRpcIdentification(const rpc::info_server::Identification& identification)
    {
        mavsdk::InfoServer::Identification obj;


            
        obj.hardware_uid = identification.hardware_uid();
            
        
            
        obj.legacy_uid = identification.legacy_uid();
            
        
        return obj;
    }





    static std::unique_ptr<rpc::info_server::Product> translateToRpcProduct(const mavsdk::InfoServer::Product &product)
    {
        auto rpc_obj = std::make_unique<rpc::info_server::Product>();


            
        rpc_obj->set_vendor_id(product.vendor_id);
            
        
            
        rpc_obj->set_vendor_name(product.vendor_name);
            
        
            
        rpc_obj->set_product_id(product.product_id);
            
        
            
        rpc_obj->set_product_name(product.product_name);
            
        

        return rpc_obj;
    }

    static mavsdk::InfoServer::Product translateFromRpcProduct(const rpc::info_server::Product& product)
    {
        mavsdk::InfoServer::Product obj;


            
        obj.vendor_id = product.vendor_id();
            
        
            
        obj.vendor_name = product.vendor_name();
            
        
            
        obj.product_id = product.product_id();
            
        
            
        obj.product_name = product.product_name();
            
        
        return obj;
    }





    static std::unique_ptr<rpc::info_server::Version> translateToRpcVersion(const mavsdk::InfoServer::Version &version)
    {
        auto rpc_obj = std::make_unique<rpc::info_server::Version>();


            
        rpc_obj->set_flight_sw_major(version.flight_sw_major);
            
        
            
        rpc_obj->set_flight_sw_minor(version.flight_sw_minor);
            
        
            
        rpc_obj->set_flight_sw_patch(version.flight_sw_patch);
            
        
            
        rpc_obj->set_flight_sw_vendor_major(version.flight_sw_vendor_major);
            
        
            
        rpc_obj->set_flight_sw_vendor_minor(version.flight_sw_vendor_minor);
            
        
            
        rpc_obj->set_flight_sw_vendor_patch(version.flight_sw_vendor_patch);
            
        
            
        rpc_obj->set_os_sw_major(version.os_sw_major);
            
        
            
        rpc_obj->set_os_sw_minor(version.os_sw_minor);
            
        
            
        rpc_obj->set_os_sw_patch(version.os_sw_patch);
            
        
            
        rpc_obj->set_flight_sw_git_hash(version.flight_sw_git_hash);
            
        
            
        rpc_obj->set_os_sw_git_hash(version.os_sw_git_hash);
            
        

        return rpc_obj;
    }

    static mavsdk::InfoServer::Version translateFromRpcVersion(const rpc::info_server::Version& version)
    {
        mavsdk::InfoServer::Version obj;


            
        obj.flight_sw_major = version.flight_sw_major();
            
        
            
        obj.flight_sw_minor = version.flight_sw_minor();
            
        
            
        obj.flight_sw_patch = version.flight_sw_patch();
            
        
            
        obj.flight_sw_vendor_major = version.flight_sw_vendor_major();
            
        
            
        obj.flight_sw_vendor_minor = version.flight_sw_vendor_minor();
            
        
            
        obj.flight_sw_vendor_patch = version.flight_sw_vendor_patch();
            
        
            
        obj.os_sw_major = version.os_sw_major();
            
        
            
        obj.os_sw_minor = version.os_sw_minor();
            
        
            
        obj.os_sw_patch = version.os_sw_patch();
            
        
            
        obj.flight_sw_git_hash = version.flight_sw_git_hash();
            
        
            
        obj.os_sw_git_hash = version.os_sw_git_hash();
            
        
        return obj;
    }




    static rpc::info_server::InfoResult::Result translateToRpcResult(const mavsdk::InfoServer::Result& result)
    {
        switch (result) {
            default:
                LogErr() << "Unknown result enum value: " << static_cast<int>(result);
            // FALLTHROUGH
            case mavsdk::InfoServer::Result::Unknown:
                return rpc::info_server::InfoResult_Result_RESULT_UNKNOWN;
            case mavsdk::InfoServer::Result::Success:
                return rpc::info_server::InfoResult_Result_RESULT_SUCCESS;
            case mavsdk::InfoServer::Result::InformationNotReceivedYet:
                return rpc::info_server::InfoResult_Result_RESULT_INFORMATION_NOT_RECEIVED_YET;
            case mavsdk::InfoServer::Result::NoSystem:
                return rpc::info_server::InfoResult_Result_RESULT_NO_SYSTEM;
        }
    }

    static mavsdk::InfoServer::Result translateFromRpcResult(const rpc::info_server::InfoResult::Result result)
    {
        switch (result) {
            default:
                LogErr() << "Unknown result enum value: " << static_cast<int>(result);
            // FALLTHROUGH
            case rpc::info_server::InfoResult_Result_RESULT_UNKNOWN:
                return mavsdk::InfoServer::Result::Unknown;
            case rpc::info_server::InfoResult_Result_RESULT_SUCCESS:
                return mavsdk::InfoServer::Result::Success;
            case rpc::info_server::InfoResult_Result_RESULT_INFORMATION_NOT_RECEIVED_YET:
                return mavsdk::InfoServer::Result::InformationNotReceivedYet;
            case rpc::info_server::InfoResult_Result_RESULT_NO_SYSTEM:
                return mavsdk::InfoServer::Result::NoSystem;
        }
    }




    grpc::Status ProvideFlightInformation(
        grpc::ServerContext* /* context */,
        const rpc::info_server::ProvideFlightInformationRequest* /* request */,
        rpc::info_server::ProvideFlightInformationResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            if (response != nullptr) {
                auto result = mavsdk::InfoServer::Result::NoSystem;
                fillResponseWithResult(response, result);
            }
            
            return grpc::Status::OK;
        }

        

        auto result = _lazy_plugin.maybe_plugin()->provide_flight_information();

        if (response != nullptr) {
            fillResponseWithResult(response, result.first);
            
            response->set_allocated_flight_info(translateToRpcFlightInfo(result.second).release());
            
        }


        return grpc::Status::OK;
    }

    grpc::Status ProvideIdentification(
        grpc::ServerContext* /* context */,
        const rpc::info_server::ProvideIdentificationRequest* /* request */,
        rpc::info_server::ProvideIdentificationResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            if (response != nullptr) {
                auto result = mavsdk::InfoServer::Result::NoSystem;
                fillResponseWithResult(response, result);
            }
            
            return grpc::Status::OK;
        }

        

        auto result = _lazy_plugin.maybe_plugin()->provide_identification();

        if (response != nullptr) {
            fillResponseWithResult(response, result.first);
            
            response->set_allocated_identification(translateToRpcIdentification(result.second).release());
            
        }


        return grpc::Status::OK;
    }

    grpc::Status ProvideProduct(
        grpc::ServerContext* /* context */,
        const rpc::info_server::ProvideProductRequest* /* request */,
        rpc::info_server::ProvideProductResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            if (response != nullptr) {
                auto result = mavsdk::InfoServer::Result::NoSystem;
                fillResponseWithResult(response, result);
            }
            
            return grpc::Status::OK;
        }

        

        auto result = _lazy_plugin.maybe_plugin()->provide_product();

        if (response != nullptr) {
            fillResponseWithResult(response, result.first);
            
            response->set_allocated_product(translateToRpcProduct(result.second).release());
            
        }


        return grpc::Status::OK;
    }

    grpc::Status ProvideVersion(
        grpc::ServerContext* /* context */,
        const rpc::info_server::ProvideVersionRequest* /* request */,
        rpc::info_server::ProvideVersionResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            if (response != nullptr) {
                auto result = mavsdk::InfoServer::Result::NoSystem;
                fillResponseWithResult(response, result);
            }
            
            return grpc::Status::OK;
        }

        

        auto result = _lazy_plugin.maybe_plugin()->provide_version();

        if (response != nullptr) {
            fillResponseWithResult(response, result.first);
            
            response->set_allocated_version(translateToRpcVersion(result.second).release());
            
        }


        return grpc::Status::OK;
    }

    grpc::Status ProvideSpeedFactor(
        grpc::ServerContext* /* context */,
        const rpc::info_server::ProvideSpeedFactorRequest* /* request */,
        rpc::info_server::ProvideSpeedFactorResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            if (response != nullptr) {
                auto result = mavsdk::InfoServer::Result::NoSystem;
                fillResponseWithResult(response, result);
            }
            
            return grpc::Status::OK;
        }

        

        auto result = _lazy_plugin.maybe_plugin()->provide_speed_factor();

        if (response != nullptr) {
            fillResponseWithResult(response, result.first);
            
            response->set_speed_factor(result.second);
            
        }


        return grpc::Status::OK;
    }


    void stop() {
        _stopped.store(true);
        for (auto& prom : _stream_stop_promises) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        }
    }

private:
    void register_stream_stop_promise(std::weak_ptr<std::promise<void>> prom) {
        // If we have already stopped, set promise immediately and don't add it to list.
        if (_stopped.load()) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        } else {
            _stream_stop_promises.push_back(prom);
        }
    }

    void unregister_stream_stop_promise(std::shared_ptr<std::promise<void>> prom) {
        for (auto it = _stream_stop_promises.begin(); it != _stream_stop_promises.end(); /* ++it */) {
            if (it->lock() == prom) {
                it = _stream_stop_promises.erase(it);
            } else {
                ++it;
            }
        }
    }

    LazyPlugin& _lazy_plugin;
    std::atomic<bool> _stopped{false};
    std::vector<std::weak_ptr<std::promise<void>>> _stream_stop_promises {};
};

} // namespace mavsdk_server
} // namespace mavsdk