// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/info_server/info_server.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include "mavsdk/plugin_base.h"

namespace mavsdk {

class System;
class InfoServerImpl;

/**
 * @brief Provide information about the hardware and/or software of a system.
 */
class InfoServer : public PluginBase {
public:
    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto info_server = InfoServer(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit InfoServer(System& system); // deprecated

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto info_server = InfoServer(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit InfoServer(std::shared_ptr<System> system); // new

    /**
     * @brief Destructor (internal use only).
     */
    ~InfoServer();

    /**
     * @brief System flight information.
     */
    struct FlightInfo {
        uint32_t time_boot_ms{}; /**< @brief Time since system boot */
        uint64_t flight_uid{}; /**< @brief Flight counter. Starts from zero, is incremented at every
                                  disarm and is never reset (even after reboot) */
    };

    /**
     * @brief Equal operator to compare two `InfoServer::FlightInfo` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const InfoServer::FlightInfo& lhs, const InfoServer::FlightInfo& rhs);

    /**
     * @brief Stream operator to print information about a `InfoServer::FlightInfo`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, InfoServer::FlightInfo const& flight_info);

    /**
     * @brief System identification.
     */
    struct Identification {
        std::string
            hardware_uid{}; /**< @brief UID of the hardware. This refers to uid2 of MAVLink. If the
                               system does not support uid2 yet, this is all zeros. */
        uint64_t legacy_uid{}; /**< @brief Legacy UID of the hardware, referred to as uid in MAVLink
                                  (formerly exposed during system discovery as UUID). */
    };

    /**
     * @brief Equal operator to compare two `InfoServer::Identification` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool
    operator==(const InfoServer::Identification& lhs, const InfoServer::Identification& rhs);

    /**
     * @brief Stream operator to print information about a `InfoServer::Identification`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream&
    operator<<(std::ostream& str, InfoServer::Identification const& identification);

    /**
     * @brief System product information.
     */
    struct Product {
        int32_t vendor_id{}; /**< @brief ID of the board vendor */
        std::string vendor_name{}; /**< @brief Name of the vendor */
        int32_t product_id{}; /**< @brief ID of the product */
        std::string product_name{}; /**< @brief Name of the product */
    };

    /**
     * @brief Equal operator to compare two `InfoServer::Product` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const InfoServer::Product& lhs, const InfoServer::Product& rhs);

    /**
     * @brief Stream operator to print information about a `InfoServer::Product`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, InfoServer::Product const& product);

    /**
     * @brief System version information.
     */
    struct Version {
        int32_t flight_sw_major{}; /**< @brief Flight software major version */
        int32_t flight_sw_minor{}; /**< @brief Flight software minor version */
        int32_t flight_sw_patch{}; /**< @brief Flight software patch version */
        int32_t flight_sw_vendor_major{}; /**< @brief Flight software vendor major version */
        int32_t flight_sw_vendor_minor{}; /**< @brief Flight software vendor minor version */
        int32_t flight_sw_vendor_patch{}; /**< @brief Flight software vendor patch version */
        int32_t os_sw_major{}; /**< @brief Operating system software major version */
        int32_t os_sw_minor{}; /**< @brief Operating system software minor version */
        int32_t os_sw_patch{}; /**< @brief Operating system software patch version */
        std::string flight_sw_git_hash{}; /**< @brief Flight software git hash */
        std::string os_sw_git_hash{}; /**< @brief Operating system software git hash */
    };

    /**
     * @brief Equal operator to compare two `InfoServer::Version` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const InfoServer::Version& lhs, const InfoServer::Version& rhs);

    /**
     * @brief Stream operator to print information about a `InfoServer::Version`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, InfoServer::Version const& version);

    /**
     * @brief Possible results returned for info requests.
     */
    enum class Result {
        Unknown, /**< @brief Unknown result. */
        Success, /**< @brief Request succeeded. */
        InformationNotReceivedYet, /**< @brief Information has not been received yet. */
        NoSystem, /**< @brief No system is connected. */
    };

    /**
     * @brief Stream operator to print information about a `InfoServer::Result`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, InfoServer::Result const& result);

    /**
     * @brief Callback type for asynchronous InfoServer calls.
     */
    using ResultCallback = std::function<void(Result)>;

    /**
     * @brief Provide flight information of the system.
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    std::pair<Result, InfoServer::FlightInfo> provide_flight_information() const;

    /**
     * @brief Provide the identification of the system.
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    std::pair<Result, InfoServer::Identification> provide_identification() const;

    /**
     * @brief Provide product information of the system.
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    std::pair<Result, InfoServer::Product> provide_product() const;

    /**
     * @brief Provide the version information of the system.
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    std::pair<Result, InfoServer::Version> provide_version() const;

    /**
     * @brief Provide the speed factor of a simulation (with lockstep a simulation can run faster or
     * slower than realtime).
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    std::pair<Result, double> provide_speed_factor() const;

    /**
     * @brief Copy constructor.
     */
    InfoServer(const InfoServer& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const InfoServer& operator=(const InfoServer&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<InfoServerImpl> _impl;
};

} // namespace mavsdk